// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "../include/fl_anna_about.h"

void fl_anna_about::cb_Close_i(Fl_Button*, void*) {
  this->hide();
}
void fl_anna_about::cb_Close(Fl_Button* o, void* v) {
  ((fl_anna_about*)(o->parent()->user_data()))->cb_Close_i(o,v);
}

fl_anna_about::fl_anna_about() {
  { about = new Fl_Double_Window(450, 215, "Artificial Neural Network Arquitecture (ANNA) 1.7");
    about->color((Fl_Color)180);
    about->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(12, 6, 430, 68, "fl_anna  is a basic application of ANNA and the FLTK library. \nFeel free to \
use ANNA under the GNU public license. for questions or suggestions feel free \
to email me:\n                 Edmanuel Torres (eetorres@@gmail.com)");
      o->color((Fl_Color)55);
      o->align(Fl_Align(165|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(3, 107, 445, 84, "FLTK Copyright  (C) 1991 Free Software Foundation, Inc. 59 Temple Place, Suit\
e 330,  Boston, MA   02111-1307  USA,    It was originally developed by  Mr. B\
ill Spitzak  and  is currently maintained by a small group  of  developers acr\
oss the world  with  central repository in the US. The FLTK project (http://ww\
w.fltk.org).");
      o->align(Fl_Align(133|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    { _inf = new Fl_Output(15, 76, 420, 25);
      _inf->box(FL_PLASTIC_THIN_DOWN_BOX);
      _inf->color(FL_GREEN);
      _inf->labelcolor((Fl_Color)59);
      _inf->align(Fl_Align(FL_ALIGN_CENTER));
      _inf->value("http://bpanna.sourceforge.net/");
    } // Fl_Output* _inf
    { Fl_Button* o = new Fl_Button(368, 187, 70, 21, "&Close");
      o->box(FL_PLASTIC_UP_BOX);
      o->color((Fl_Color)81);
      o->labelcolor((Fl_Color)57);
      o->callback((Fl_Callback*)cb_Close);
    } // Fl_Button* o
    about->set_non_modal();
    about->end();
  } // Fl_Double_Window* about
}

void fl_anna_about::show() {
  about->show();
}

void fl_anna_about::hide() {
  about->hide();
}
