// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef fl_anna_set_h
#define fl_anna_set_h
#include <FL/Fl.H>
#include <msmvtl/tmatrix.h>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Button.H>
#include<fl_anna_display.h>
#include <FL/Fl_Spinner.H>

class fl_anna_set {
public:
  TVector<unsigned int> _nstr; 
  TVector<unsigned int> _n_actf; 
  unsigned int _in, _out, _num_ly; 
  ~fl_anna_set();
  fl_anna_set();
  Fl_Double_Window *track;
  Fl_Value_Input *_ly_1;
  Fl_Value_Input *_ly_2;
  Fl_Value_Input *_ly_3;
  Fl_Choice *choice_activation_function_1;
  Fl_Choice *choice_activation_function_2;
  Fl_Choice *choice_activation_function_3;
private:
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
  inline void cb_Display_i(Fl_Button*, void*);
  static void cb_Display(Fl_Button*, void*);
  inline void cb_Apply_i(Fl_Button*, void*);
  static void cb_Apply(Fl_Button*, void*);
public:
  Fl_Spinner *_nl;
private:
  inline void cb__nl_i(Fl_Spinner*, void*);
  static void cb__nl(Fl_Spinner*, void*);
public:
  Fl_Spinner *nop;
private:
  inline void cb_nop_i(Fl_Spinner*, void*);
  static void cb_nop(Fl_Spinner*, void*);
public:
  void show(unsigned int _inp, unsigned int _op);
  void structure(TVector<unsigned int>& s);
  void chk_layers(void);
  TVector<unsigned int>& structure(void);
  TVector<unsigned int>& functions(void);
  void hide();
  int visible();
};
#endif
